### ISSUE TITLE
Content is visible on SSR (Nuxt 3)

### ISSUE THREAD

**Issue by mrleblanc101** [southcoastweb/vue3-slide-up-down#16]
My ref default to false, but we see the content on the server-side before hydration.
Then the content is hidden when the component is mounted.

![2023-01-07 21 14 46](https://user-images.githubusercontent.com/17392251/211177683-3b8eb3fa-c589-4d47-b282-b5cd6046deeb.gif)

**Comment by mrleblanc101** [comment]
Here is the Server-side generated content (by disabling JavaScript).
I fixed it by wrapping the component in `<ClientOnly>`, but that's not the right solution.
<img width="1912" alt="Capture d’écran, le 2023-01-07 à 21 10 38" src="https://user-images.githubusercontent.com/17392251/211177587-4a9bba83-758a-4a36-be50-10a4be9ee595.png">

**Comment by lorado** [comment]
@mrleblanc101 hey buddy, I had same issue. 
I really like having libraries which works out of the box, but sometimes its better to get inspiration from these libraries and write your own implementation. I decided to implement it inside my project directly, while getting primary code from this repository.

so first mainly to fix the issue [this code part](https://github.com/craigrileyuk/vue3-slide-up-down/blob/main/src/index.js#L112-L114) should be moved outside of `onMounted()` hook.

Here is my implementation of the component in TS. I also removed parts im not interested in and refactored a little. Feel free to use it: https://gist.github.com/lorado/fc6af5a7b249144877514073812252a7

**Comment by Atinux** [comment]
Thanks for sharing @lorado 🚀 

Was looking at a solution for Vue 3 and found this issue and you talking about Nuxt 3 💚

**Comment by mrleblanc101** [comment]
@craigrileyuk @lorado @Atinux I'll open a PR

**Comment by mrleblanc101** [comment]
Nvm it doesn't seem to work.
I don't have time to investigate right now, as @lorado Gist has many other change

**Comment by mrleblanc101** [comment]
I think I need more something like this https://github.com/whyayen/transition-to-height-auto-with-vue/blob/master/src/components/TransitionExpand.vue so I'll probably just convert it to Vue 3 / Nuxt 3.

**Comment by Atinux** [comment]
> I think I need more something like this [Vue-Transition-Expand](https://github.com/whyayen/transition-to-height-auto-with-vue/blob/master/src/components/TransitionExpand.vue) so I'll probably just convert it to Vue 3 / Nuxt 3.

If you did it and have the code somewhere, I would love to see it @mrleblanc101

**Comment by lorado** [comment]
> I think I need more something like this [Vue-Transition-Expand](https://github.com/whyayen/transition-to-height-auto-with-vue/blob/master/src/components/TransitionExpand.vue) so I'll probably just convert it to Vue 3 / Nuxt 3.

this is very interesting approach. I'll migrate and post here soon

**Comment by lorado** [comment]
> Nvm it doesn't seem to work.
> I don't have time to investigate right now, as @lorado Gist has many other change

to fix the actually issue in this repo, you just have to fix this:
[this code part](https://github.com/craigrileyuk/vue3-slide-up-down/blob/main/src/index.js#L112-L114) should be moved outside of onMounted() hook.

**Comment by mrleblanc101** [comment]
@lorado I moved the whole if/else and no it doesn't fix the issue. Or it created other issue, I don't remember exactly

**Comment by lorado** [comment]
@mrleblanc101 @Atinux 
I like the new component much more.
https://gist.github.com/lorado/0dde32c3d769a5f2163f48f8d7496a18

**Comment by mrleblanc101** [comment]
@Atinux I made a NPM package based on @lorado's work, I miss a Nuxt module and TypeScript definition.
I'm pretty new to all of this so feel free to open issues or PR.
https://github.com/mrleblanc101/vue3-transition-expand
https://www.npmjs.com/package/vue3-transition-expand

**Comment by Atinux** [comment]
Nice @mrleblanc101 

I don't think a module is necessary for such Vue plugin, a simple example if more than enough!

Would be nice to have an example on Stackblitz and link in the readme

**Comment by Atinux** [comment]
Also, why using a `v-model` since you don't emit any changes? I think an `active` or `visible` property (boolean) is enough

**Comment by mrleblanc101** [comment]
@Atinux 
> Would be nice to have an example on Stackblitz and link in the readme

I'll look into adding a Stackblitz tonight

> Also, why using a v-model since you don't emit any changes? I think an active or visible property (boolean) is enough

True, I thought `v-model` was closed to the `v-if` it replaced on the slot root element, but I'll change for `visible` or `expanded` props.

> I don't think a module is necessary for such Vue plugin, a simple example if more than enough!

I guess you are right, but I'll end up copy-pasting the same custom Nuxt plugin to load this Vue plugin in every project ?
I think we can't send options to Nuxt plugin directly, that's why I wanted to add a module that load the plugin.

Is something like this possible with Nuxt plugin ?
```
modules: [
    // Providing options
    ['vue3-transition-expand', { duration: 3000 }],
],
```

I'm pretty new to TS too, so if you have any pointer on how I can add TS definition, it would be greatly appreaciated.
Currently I just added a `@ts-ignore` to my import.
```
// @ts-ignore
import TransitionExpand from 'vue3-transition-expand';
```

**Comment by Atinux** [comment]
Actually I would rather have a way to import the component right away in my current pages instead of setting a plugin for a global component that can be used only on specific areas of my app.

```ts
import { TransitionExpand } from 'vue3-transition-expand'
```

Would be best, for TS sadly I am not the best person for it 😅

**Comment by mrleblanc101** [comment]
@Atinux You can already do this ! I guess that's how most people will use the plugin so I guess just a Nuxt Plugin exemple is fine, you are right

**Comment by mrleblanc101** [comment]
@Atinux @lorado Updated with TS and `expanded` props instead of v-model. Haven't had time to look at StackBlitz yet.

**Comment by lorado** [comment]
> I am also using this as a plugin on my Nuxt 3 Project. But the content is still visible on server.
> Is there any progress concerning this?

First of all - the repo owner seem to have a problem with open source... we had a great discussion and multiple solutions posted here, and he just removed them all. Oh well.. at least you @Milenoi will hopefully get this message over email.

You can either use my modified version of the SlideUpDown component, which fixes the issue: https://gist.github.com/lorado/fc6af5a7b249144877514073812252a7

Alternatively you can check this gist: https://gist.github.com/lorado/0dde32c3d769a5f2163f48f8d7496a18
It has slightly different approach than here but this library partially inspired my solution. There are multiple solutions. Hope this will help you. I personally use transition-expand in my projects.
